# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-09 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
